In [1]:
import numpy as np
import tensorflow as tf
import gym

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
benchmark = gym.benchmark_spec('Atari40M')

In [3]:
task = benchmark.tasks[3]

In [6]:
from run_dqn_atari import *

In [7]:
env = get_env(task, 0)

[2018-06-08 23:37:20,714] Making new env: PongNoFrameskip-v4
[2018-06-08 23:37:21,102] Clearing 2 monitor files from previous run (because force=True was provided)


In [10]:
action = env.action_space.sample()

In [13]:
observation = env.reset()

[2018-06-08 23:38:59,068] Starting new video recorder writing to /tmp/hw3_vid_dir2/gym/openaigym.video.0.6079.video000000.mp4


In [15]:
observation.shape

(84, 84, 1)

In [16]:
env.action_space

Discrete(6)

In [17]:
env.observation_space.shape

(84, 84, 1)

In [28]:
sample_space = tf.placeholder(shape = (64, 84, 84, 4), dtype = tf.float32)

In [19]:
num_actions = env.action_space.n

In [21]:
num_actions

6

In [29]:
model1 = atari_model(sample_space, num_actions, "test2")

In [30]:
model1.get_shape()

TensorShape([Dimension(64), Dimension(6)])

In [32]:
v1 = tf.Variable([1,6,3,4,5,0], dtype = tf.float32)

In [33]:
sess = tf.InteractiveSession()

In [36]:
sess.run(tf.argmax(v1))

1

In [57]:
sess.run(tf.global_variables_initializer())

In [37]:
sess.run(tf.reduce_max(v1))

6.0

In [39]:
v2 = tf.Variable([1,6,3,4,5,0], dtype = tf.uint8)

In [41]:
sess.run(tf.one_hot(v2, 7))

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [46]:
sess.run(0.999 * (1 - v1) * v1)

array([  0.        , -29.96999931,  -5.99399996, -11.98799992,
       -19.97999954,   0.        ], dtype=float32)

In [56]:
ph2 = tf.placeholder(tf.float32, shape = [6])
optimizer = tf.train.AdamOptimizer().minimize(tf.nn.l2_loss(tf.reduce_max(ph2) - tf.reduce_max(v1)))

In [64]:
print(sess.run(optimizer, {ph2: [1,6,3,4,5,0]}))

None


In [66]:
a = tf.placeholder(dtype=tf.float32, shape=[4])
b = tf.reduce_max(a)
c = tf.gradients([b], [a])[0]
with tf.Session() as sess:
    v = np.asarray([1, 2, 3, 4], dtype='float32')
    print(sess.run(c, feed_dict={a:v}))

[ 0.  0.  0.  1.]


In [67]:
import gym

In [68]:
benchmark = gym.benchmark_spec('Atari40M')

In [69]:
task = benchmark.tasks[3]

In [70]:
task.max_timesteps

40000000

[2018-06-14 13:16:55,320] Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/hw3_vid_dir2/gym')
